# CodeRabbit Configuration
# Ignore automatic updates from workflows

# Skip review for workflow commits
reviews:
  auto_review: false
  ignore_patterns:
    - "**/README.md"  # Skip README updates from aggregator

# Don't block automated commits
path_filters:
  excluded:
    - README.md

# Allow workflow commits to bypass review
commit_message_patterns:
  skip_review:
    - "Updated AI-Pulse:"
    - "[skip ci]"
    - "github-actions[bot]"

# Auto-approve workflow PRs
auto_approve:
  enabled: true
  conditions:
    - author: "github-actions[bot]"
    - commit_message_contains: "Updated AI-Pulse:"
